//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaidWeekPlanner.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class areas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal areas() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaidWeekPlanner.Ressources.areas", typeof(areas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EoD.
        /// </summary>
        internal static string EODLabel {
            get {
                return ResourceManager.GetString("EODLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End of Dragons.
        /// </summary>
        internal static string EODTooltip {
            get {
                return ResourceManager.GetString("EODTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IBS.
        /// </summary>
        internal static string IBSLabel {
            get {
                return ResourceManager.GetString("IBSLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Icebrood Saga.
        /// </summary>
        internal static string IBSTooltip {
            get {
                return ResourceManager.GetString("IBSTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Soto.
        /// </summary>
        internal static string SOTOLabel {
            get {
                return ResourceManager.GetString("SOTOLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Secrets of the Obscure.
        /// </summary>
        internal static string SOTOTooltip {
            get {
                return ResourceManager.GetString("SOTOTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à VoE.
        /// </summary>
        internal static string VOELabel {
            get {
                return ResourceManager.GetString("VOELabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visions of Eternity.
        /// </summary>
        internal static string VOETooltip {
            get {
                return ResourceManager.GetString("VOETooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W1.
        /// </summary>
        internal static string W1Label {
            get {
                return ResourceManager.GetString("W1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W1.
        /// </summary>
        internal static string W1Tooltip {
            get {
                return ResourceManager.GetString("W1Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W2.
        /// </summary>
        internal static string W2Label {
            get {
                return ResourceManager.GetString("W2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W2.
        /// </summary>
        internal static string W2Tooltip {
            get {
                return ResourceManager.GetString("W2Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W3.
        /// </summary>
        internal static string W3Label {
            get {
                return ResourceManager.GetString("W3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W3.
        /// </summary>
        internal static string W3Tooltip {
            get {
                return ResourceManager.GetString("W3Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W4.
        /// </summary>
        internal static string W4Label {
            get {
                return ResourceManager.GetString("W4Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W4.
        /// </summary>
        internal static string W4Tooltip {
            get {
                return ResourceManager.GetString("W4Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W5.
        /// </summary>
        internal static string W5Label {
            get {
                return ResourceManager.GetString("W5Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W5.
        /// </summary>
        internal static string W5Tooltip {
            get {
                return ResourceManager.GetString("W5Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W6.
        /// </summary>
        internal static string W6Label {
            get {
                return ResourceManager.GetString("W6Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W6.
        /// </summary>
        internal static string W6Tooltip {
            get {
                return ResourceManager.GetString("W6Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W7.
        /// </summary>
        internal static string W7Label {
            get {
                return ResourceManager.GetString("W7Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W7.
        /// </summary>
        internal static string W7Tooltip {
            get {
                return ResourceManager.GetString("W7Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W8.
        /// </summary>
        internal static string W8Label {
            get {
                return ResourceManager.GetString("W8Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W8.
        /// </summary>
        internal static string W8Tooltip {
            get {
                return ResourceManager.GetString("W8Tooltip", resourceCulture);
            }
        }
    }
}
