//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaidWeekPlanner.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class encounters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal encounters() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaidWeekPlanner.Ressources.encounters", typeof(encounters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adina.
        /// </summary>
        internal static string adinaLabel {
            get {
                return ResourceManager.GetString("adinaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cardinal Adina.
        /// </summary>
        internal static string adinaTooltip {
            get {
                return ResourceManager.GetString("adinaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aetherblade.
        /// </summary>
        internal static string aetherblade_hideoutLabel {
            get {
                return ResourceManager.GetString("aetherblade_hideoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aetherblade Hideout.
        /// </summary>
        internal static string aetherblade_hideoutTooltip {
            get {
                return ResourceManager.GetString("aetherblade_hideoutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trio.
        /// </summary>
        internal static string bandit_trioLabel {
            get {
                return ResourceManager.GetString("bandit_trioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bandit Trio.
        /// </summary>
        internal static string bandit_trioTooltip {
            get {
                return ResourceManager.GetString("bandit_trioTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BS.
        /// </summary>
        internal static string boneskinnerLabel {
            get {
                return ResourceManager.GetString("boneskinnerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Boneskinner.
        /// </summary>
        internal static string boneskinnerTooltip {
            get {
                return ResourceManager.GetString("boneskinnerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cairn.
        /// </summary>
        internal static string cairnLabel {
            get {
                return ResourceManager.GetString("cairnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cairn.
        /// </summary>
        internal static string cairnTooltip {
            get {
                return ResourceManager.GetString("cairnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Camp.
        /// </summary>
        internal static string campLabel {
            get {
                return ResourceManager.GetString("campLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ruined Camp.
        /// </summary>
        internal static string campTooltip {
            get {
                return ResourceManager.GetString("campTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CA.
        /// </summary>
        internal static string conjured_amalgamateLabel {
            get {
                return ResourceManager.GetString("conjured_amalgamateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conjured Amalgamate.
        /// </summary>
        internal static string conjured_amalgamateTooltip {
            get {
                return ResourceManager.GetString("conjured_amalgamateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CO.
        /// </summary>
        internal static string cosmic_observatoryLabel {
            get {
                return ResourceManager.GetString("cosmic_observatoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cosmic Observatory.
        /// </summary>
        internal static string cosmic_observatoryTooltip {
            get {
                return ResourceManager.GetString("cosmic_observatoryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decima.
        /// </summary>
        internal static string decimaLabel {
            get {
                return ResourceManager.GetString("decimaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decima, the Stormsinger.
        /// </summary>
        internal static string decimaTooltip {
            get {
                return ResourceManager.GetString("decimaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deimos.
        /// </summary>
        internal static string deimosLabel {
            get {
                return ResourceManager.GetString("deimosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deimos.
        /// </summary>
        internal static string deimosTooltip {
            get {
                return ResourceManager.GetString("deimosTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Escort.
        /// </summary>
        internal static string escortLabel {
            get {
                return ResourceManager.GetString("escortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Escort.
        /// </summary>
        internal static string escortTooltip {
            get {
                return ResourceManager.GetString("escortTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fraenir.
        /// </summary>
        internal static string fraenir_of_jormagLabel {
            get {
                return ResourceManager.GetString("fraenir_of_jormagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fraenir of Jormag.
        /// </summary>
        internal static string fraenir_of_jormagTooltip {
            get {
                return ResourceManager.GetString("fraenir_of_jormagTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gate.
        /// </summary>
        internal static string gateLabel {
            get {
                return ResourceManager.GetString("gateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gate.
        /// </summary>
        internal static string gateTooltip {
            get {
                return ResourceManager.GetString("gateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gorseval.
        /// </summary>
        internal static string gorsevalLabel {
            get {
                return ResourceManager.GetString("gorsevalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gorseval.
        /// </summary>
        internal static string gorsevalTooltip {
            get {
                return ResourceManager.GetString("gorsevalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Greer.
        /// </summary>
        internal static string greerLabel {
            get {
                return ResourceManager.GetString("greerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Greer, the Blightbringer.
        /// </summary>
        internal static string greerTooltip {
            get {
                return ResourceManager.GetString("greerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HT.
        /// </summary>
        internal static string harvest_templeLabel {
            get {
                return ResourceManager.GetString("harvest_templeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Harvest Temple.
        /// </summary>
        internal static string harvest_templeTooltip {
            get {
                return ResourceManager.GetString("harvest_templeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à KO.
        /// </summary>
        internal static string kaineng_overlookLabel {
            get {
                return ResourceManager.GetString("kaineng_overlookLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kaineng Overlook.
        /// </summary>
        internal static string kaineng_overlookTooltip {
            get {
                return ResourceManager.GetString("kaineng_overlookTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à KC.
        /// </summary>
        internal static string keep_constructLabel {
            get {
                return ResourceManager.GetString("keep_constructLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keep Construct.
        /// </summary>
        internal static string keep_constructTooltip {
            get {
                return ResourceManager.GetString("keep_constructTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kela.
        /// </summary>
        internal static string kelaLabel {
            get {
                return ResourceManager.GetString("kelaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kela.
        /// </summary>
        internal static string kelaTooltip {
            get {
                return ResourceManager.GetString("kelaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Matthias.
        /// </summary>
        internal static string matthiasLabel {
            get {
                return ResourceManager.GetString("matthiasLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Matthias.
        /// </summary>
        internal static string matthiasTooltip {
            get {
                return ResourceManager.GetString("matthiasTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MO.
        /// </summary>
        internal static string mursaat_overseerLabel {
            get {
                return ResourceManager.GetString("mursaat_overseerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mursaat Overseer.
        /// </summary>
        internal static string mursaat_overseerTooltip {
            get {
                return ResourceManager.GetString("mursaat_overseerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OLC.
        /// </summary>
        internal static string old_lion_courtLabel {
            get {
                return ResourceManager.GetString("old_lion_courtLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Old Lion&apos;s Court.
        /// </summary>
        internal static string old_lion_courtTooltip {
            get {
                return ResourceManager.GetString("old_lion_courtTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à QTP.
        /// </summary>
        internal static string qadim_the_peerlessLabel {
            get {
                return ResourceManager.GetString("qadim_the_peerlessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qadim the Peerless.
        /// </summary>
        internal static string qadim_the_peerlessTooltip {
            get {
                return ResourceManager.GetString("qadim_the_peerlessTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qadim.
        /// </summary>
        internal static string qadimLabel {
            get {
                return ResourceManager.GetString("qadimLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qadim.
        /// </summary>
        internal static string qadimTooltip {
            get {
                return ResourceManager.GetString("qadimTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à River.
        /// </summary>
        internal static string river_of_soulsLabel {
            get {
                return ResourceManager.GetString("river_of_soulsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à River of Souls.
        /// </summary>
        internal static string river_of_soulsTooltip {
            get {
                return ResourceManager.GetString("river_of_soulsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sabetha.
        /// </summary>
        internal static string sabethaLabel {
            get {
                return ResourceManager.GetString("sabethaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sabetha.
        /// </summary>
        internal static string sabethaTooltip {
            get {
                return ResourceManager.GetString("sabethaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sabir.
        /// </summary>
        internal static string sabirLabel {
            get {
                return ResourceManager.GetString("sabirLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cardinal Sabir.
        /// </summary>
        internal static string sabirTooltip {
            get {
                return ResourceManager.GetString("sabirTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Samarog.
        /// </summary>
        internal static string samarogLabel {
            get {
                return ResourceManager.GetString("samarogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Samarog.
        /// </summary>
        internal static string samarogTooltip {
            get {
                return ResourceManager.GetString("samarogTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shiverpeaks.
        /// </summary>
        internal static string shiverpeaks_passLabel {
            get {
                return ResourceManager.GetString("shiverpeaks_passLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shiverpeaks Pass.
        /// </summary>
        internal static string shiverpeaks_passTooltip {
            get {
                return ResourceManager.GetString("shiverpeaks_passTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Slothasor.
        /// </summary>
        internal static string slothasorLabel {
            get {
                return ResourceManager.GetString("slothasorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Slothasor.
        /// </summary>
        internal static string slothasorTooltip {
            get {
                return ResourceManager.GetString("slothasorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SH.
        /// </summary>
        internal static string soulless_horrorLabel {
            get {
                return ResourceManager.GetString("soulless_horrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Soulless Horror.
        /// </summary>
        internal static string soulless_horrorTooltip {
            get {
                return ResourceManager.GetString("soulless_horrorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Woods.
        /// </summary>
        internal static string spirit_woodsLabel {
            get {
                return ResourceManager.GetString("spirit_woodsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spirit Woods.
        /// </summary>
        internal static string spirit_woodsTooltip {
            get {
                return ResourceManager.GetString("spirit_woodsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statues.
        /// </summary>
        internal static string statues_of_grenthLabel {
            get {
                return ResourceManager.GetString("statues_of_grenthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statues Of Grenth.
        /// </summary>
        internal static string statues_of_grenthTooltip {
            get {
                return ResourceManager.GetString("statues_of_grenthTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cerus.
        /// </summary>
        internal static string temple_of_febeLabel {
            get {
                return ResourceManager.GetString("temple_of_febeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temple of Febe.
        /// </summary>
        internal static string temple_of_febeTooltip {
            get {
                return ResourceManager.GetString("temple_of_febeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TL.
        /// </summary>
        internal static string twin_largosLabel {
            get {
                return ResourceManager.GetString("twin_largosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Twin Largos.
        /// </summary>
        internal static string twin_largosTooltip {
            get {
                return ResourceManager.GetString("twin_largosTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à twisted.
        /// </summary>
        internal static string twisted_castleLabel {
            get {
                return ResourceManager.GetString("twisted_castleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Twisted Castle.
        /// </summary>
        internal static string twisted_castleTooltip {
            get {
                return ResourceManager.GetString("twisted_castleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ura.
        /// </summary>
        internal static string uraLabel {
            get {
                return ResourceManager.GetString("uraLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ura, the Steamshrieker.
        /// </summary>
        internal static string uraTooltip {
            get {
                return ResourceManager.GetString("uraTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à VG.
        /// </summary>
        internal static string vale_guardianLabel {
            get {
                return ResourceManager.GetString("vale_guardianLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vale Guardian.
        /// </summary>
        internal static string vale_guardianTooltip {
            get {
                return ResourceManager.GetString("vale_guardianTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voices.
        /// </summary>
        internal static string voice_and_clawLabel {
            get {
                return ResourceManager.GetString("voice_and_clawLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voice of the Fallen and Claw of the Fallen.
        /// </summary>
        internal static string voice_and_clawTooltip {
            get {
                return ResourceManager.GetString("voice_and_clawTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dhuum.
        /// </summary>
        internal static string voice_in_the_voidLabel {
            get {
                return ResourceManager.GetString("voice_in_the_voidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voice In The Void.
        /// </summary>
        internal static string voice_in_the_voidTooltip {
            get {
                return ResourceManager.GetString("voice_in_the_voidTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Whisper.
        /// </summary>
        internal static string whisper_of_jormagLabel {
            get {
                return ResourceManager.GetString("whisper_of_jormagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Whisper of Jormag.
        /// </summary>
        internal static string whisper_of_jormagTooltip {
            get {
                return ResourceManager.GetString("whisper_of_jormagTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Xera.
        /// </summary>
        internal static string xeraLabel {
            get {
                return ResourceManager.GetString("xeraLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Xera.
        /// </summary>
        internal static string xeraTooltip {
            get {
                return ResourceManager.GetString("xeraTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XJJ.
        /// </summary>
        internal static string xunlai_jade_junkyardLabel {
            get {
                return ResourceManager.GetString("xunlai_jade_junkyardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Xunlai Jade Junkyard.
        /// </summary>
        internal static string xunlai_jade_junkyardTooltip {
            get {
                return ResourceManager.GetString("xunlai_jade_junkyardTooltip", resourceCulture);
            }
        }
    }
}
